# Generated by Django 4.1 on 2022-08-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('September', models.DateField()),
                ('October', models.DateField()),
                ('November', models.DateField()),
            ],
        ),
    ]
