# Generated by Django 4.1 on 2022-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torquay_towers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('party_size', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('number_nights', models.IntegerField()),
            ],
        ),
    ]
