# Generated by Django 4.1 on 2022-08-14 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_post_category_alter_post_released_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='psots',
            new_name='posts',
        ),
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 8, 4, 8, 726261)),
        ),
    ]
