# Generated by Django 4.1 on 2022-08-14 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_psots_category_posts_alter_post_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 8, 4, 44, 438760)),
        ),
    ]
