# Generated by Django 4.1 on 2022-08-11 12:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
