# Generated by Django 4.1 on 2022-08-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hobbies",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile", name="image", field=models.URLField(null=True),
        ),
    ]
