# Generated by Django 4.1 on 2022-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_alter_gif_model_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif_model',
            name='likes',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='gif_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
