# Generated by Django 4.1 on 2022-08-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0005_alter_gif_model_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.gif_model')),
            ],
        ),
    ]
