# Generated by Django 4.1 on 2022-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dept_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('credits', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('grading_method', models.CharField(max_length=200)),
                ('gen_ed', models.CharField(max_length=200)),
                ('core', models.CharField(max_length=50)),
                ('relationships', models.CharField(max_length=1000)),
                ('sections', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
