# Generated by Django 4.1 on 2022-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
