# Generated by Django 4.1 on 2022-08-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0004_alter_courseinfo_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='core',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='credits',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='department',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='dept_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='semester',
            field=models.CharField(max_length=500),
        ),
    ]
