# Generated by Django 4.1 on 2022-08-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0005_alter_courseinfo_core_alter_courseinfo_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
