# Generated by Django 4.1 on 2022-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0006_alter_courseinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='core',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='credits',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='dept_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='gen_ed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='grading_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='relationships',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='sections',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='semester',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
