# Generated by Django 4.1 on 2022-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0007_alter_courseinfo_core_alter_courseinfo_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='core',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='gen_ed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='grading_method',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='relationships',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='sections',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
