# Generated by Django 4.1 on 2022-09-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0008_alter_courseinfo_core_alter_courseinfo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=3000)),
            ],
        ),
    ]
