# Generated by Django 4.1 on 2022-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0009_professors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='course_id',
            field=models.CharField(max_length=5000),
        ),
    ]
