# Generated by Django 4.1 on 2022-09-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testudo_app', '0011_savedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcourses',
            name='a',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
